# Generated by Django 3.1.2 on 2020-12-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupform',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
